[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:ollama]
command=ollama serve
environment=OLLAMA_MODELS="/workspace/ollama",OLLAMA_HOST="0.0.0.0:11434",OLLAMA_KEEP_ALIVE="-1"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=0

[program:model]
command=python -m uvicorn app:app --host 0.0.0.0 --port 8000
directory=/model
environment=PROMPTS_ENCRYPTION_KEY="%(ENV_PROMPTS_ENCRYPTION_KEY)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1
startsecs=3

[program:bot]
command=python -m bratbot
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=2
startsecs=5

[program:bonniebot]
command=python -m bonniebot
directory=/app
environment=BONNIEBOT_REDIS_URL="%(ENV_REDIS_URL)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=3
startsecs=5
